# Project: c
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = c/basic_1.o
LINKOBJ  = c/basic_1.o
LIBS     = -L"C:/Users/Alaska/Documents/escola/aplicacoes/dev_cpp/Dev-Cpp/MinGW64/lib" -L"C:/Users/Alaska/Documents/escola/aplicacoes/dev_cpp/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/Alaska/Documents/escola/aplicacoes/dev_cpp/Dev-Cpp/MinGW64/include" -I"C:/Users/Alaska/Documents/escola/aplicacoes/dev_cpp/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/Alaska/Documents/escola/aplicacoes/dev_cpp/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/Alaska/Documents/escola/aplicacoes/dev_cpp/Dev-Cpp/MinGW64/include" -I"C:/Users/Alaska/Documents/escola/aplicacoes/dev_cpp/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/Alaska/Documents/escola/aplicacoes/dev_cpp/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/Alaska/Documents/escola/aplicacoes/dev_cpp/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = c.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

c/basic_1.o: c/basic_1.c
	$(CC) -c c/basic_1.c -o c/basic_1.o $(CFLAGS)
